
apiVersion: apps/v1
kind: Deployment

metadata:
  name: deploy
  labels:
    app: deployment-app

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: deployment-app
  replicas: 5
  template:
    metadata:
      name: deploy
      labels:
        app: deployment-app
    spec:
      containers:
      - name: deploy
        image: nginx:latest
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: deploy
spec:
  selector:
    app: deployment-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
