
apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: svc
  labels:
    app: svcapp

spec:
  replicas: 5
  selector:
    matchExpressions:
    - {key: app, operator: In, values: [nginx-app, replica-set],}

  template:
    metadata:
      labels:
        name: nginx-app
        app: nginx-app

    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
