
apiVersion: v1
kind: ReplicationController

metadata:
  name: rpc
  labels:
    app: rpcapp

spec:
  replicas: 5
  selector:
    app: rpcapp

  template:
    metadata:
      labels:
        app: rpcapp
        name: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
